name: crypto_coins_list
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.7.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1



flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.png
   
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
  macos:
    generate: true
    image_path: "assets/logo/logo.png"